### PR TITLE
feat: add logo

### PR DESCRIPTION
**Pull request by exrol**
Logo contribution

### CODE REVIEW

**Comment by exrol** [comment]
Feel free to add the hacktoberfest-accepted label ;-)

**Comment by 0Hughman0** [comment]
Hi!

This is great! Thanks for the contribution!

I really like the flask shape.

If you have the time, I am wondering if the `>_` would be a bit more clear if it was a bit smaller, so it's all in view and maybe in a block colour?

Otherwise I think it's super cool.

Next step is to incorporate the logo into the appropriate places (the docs, README and the jupyterlab extension... maybe other places?). I can take care of that, unless you are keen.

**Comment by exrol** [comment]
I will make a second version / variation :+1:

**Comment by exrol** [comment]
Added a logo variation hope you'll like it

**Comment by 0Hughman0** [comment]
Yes, I definitely prefer this one, it looks a bit like it's winking!

If you could just rename the file to `logo.png` and get rid of `logo_1.png` that would be great. I'd be happy to merge at this point.

If you are feeling keen, you could work out how to add this logo to the docs.

We use the Read-the-docs sphinx theme and they have info on how to configure a logo here:

https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#adding-a-logo

The source for the docs lives in the doc_src directory.

Instructions on how to build the docs locally here are found here:

https://0hughman0.github.io/Cassini/latest/contributing.html#id3

Thanks!

**Comment by exrol** [comment]
Hi @0Hughman0  :wave: ,

Clean done, i added logo path as mentioned in Sphinx documentation.  But I'm not familiar with it and haven't setup Sphinx local environment to test it.

**Comment by 0Hughman0** [comment]
Ok great. I've checked this locally and I think it's looking good.

Thanks for the contribution.

**Comment by 0Hughman0** [comment]
Docs are now updated, you can see the new logo in the docs here:

https://0hughman0.github.io/Cassini/latest/quickstart.html

**Comment by exrol** [comment]
Great, wish you the best for the future :-) bye :wave:

**Pull request merged**
